Add v as short arg
RedisLabs/memtier_benchmark pull request #145
Opened 2020-10-18 15:58 UTC by hbina

Related issue https://github.com/RedisLabs/memtier_benchmark/issues/139

TIL about Linux's [optarg](https://man7.org/linux/man-pages/man3/getopt.3.html).

2020-10-20 11:21 UTC, YaacovHazan commented
@hbina why not just to fix the existing -v option?

2020-10-20 11:42 UTC, hbina commented
Hmm well you are right, I could have just fixed the old 'v'. IDK which is preferred, but you can edit this commit if you prefer that.

2020-10-20 14:28 UTC, hbina commented
I have applied your suggestion and fixed help string to also display short name for `--help. The diff is a lot smaller now.

2020-10-20 15:36 UTC, yaacovhazan-Redislabs requested changes

2020-10-20 15:36 UTC, yaacovhazan-Redislabs commented on memtier_benchmark.cpp
> +            "  -o  --out-file=FILE            Name of output file (default: stdout)\n"
pls add ","

2020-10-20 15:36 UTC, yaacovhazan-Redislabs commented on memtier_benchmark.cpp
> +            "  -h  --help                     Display this help\n"
pls add ","

2020-10-21 11:47 UTC, yaacovhazan-Redislabs approved these changes

2020-10-21 12:10 UTC, merged

2020-10-21 12:11 UTC, yaacovhazan-Redislabs commented
thank you @hbina for the PR... merged